// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetosJogosAPI.Context;

#nullable disable

namespace ProjetosJogosAPI.Migrations
{
    [DbContext(typeof(ProjetoJogosContext))]
    [Migration("20250408130049_Jogos")]
    partial class Jogos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetosJogosAPI.Domains.Jogo", b =>
                {
                    b.Property<Guid>("jogoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeDoJogo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Plataforma")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("jogoID");

                    b.HasIndex("NomeDoJogo")
                        .IsUnique();

                    b.ToTable("Jogo");
                });

            modelBuilder.Entity("ProjetosJogosAPI.Domains.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JogoID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(80)");

                    b.HasKey("UsuarioID");

                    b.HasIndex("JogoID");

                    b.HasIndex("NickName")
                        .IsUnique();

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ProjetosJogosAPI.Domains.Usuario", b =>
                {
                    b.HasOne("ProjetosJogosAPI.Domains.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");
                });
#pragma warning restore 612, 618
        }
    }
}
